### ISSUE TITLE
Rhino 1.7.14

### ISSUE THREAD

**Issue by tuchida** [jser/ping#167]
---
title: Release Rhino 1.7.14 · mozilla/rhino
url: https://github.com/mozilla/rhino/releases/tag/Rhino1_7_14_Release

---

GraalJSやNashornに比べるとかなりレガシーですが、今回PromiseやBigIntに対応しました。

**Comment by azu** [comment]
ありがとうございます！
https://github.com/jser/jser.info/commit/bea34293ddb7e3d8afc2f51d0121183a796d02b7 で追加しました！
